apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: link_service
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/bbakla/hands-on-microservices-kubernetes.git
    targetRevision: HEAD
    path: svc/link_service/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: hands-on-kubernetes

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

