apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-manager
  labels:
    svc: link
    app: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: link
      app: manager
  template:
    metadata:
      labels:
        svc: link
        app: manager
    spec:
      containers:
      - name: link-manager
        image: bbakla/delinkcious-link:0.3.1
        ports:
        - containerPort: 8080
       # envFrom:
        #  - configMapRef:
       #      name: link-service-conf
        volumeMounts:
          - mountPath: /etc/config
            name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: link-service-conf
   #   restartPolicy: OnFailure

---
apiVersion: v1
kind: Service
metadata:
  name: link-manager
spec:
  ports:
  - port:  8080
  selector:
    svc: link
    app: manager
